spring:
  application:
    name: waterlily
    datasource:
      url: jdbc:h2:file:./data/waterlily;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
      driver-class-name: org.h2.Driver
      username: sa
      password: ""

server:
  port: 8080
  servlet:
    context-path: /api


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

app:
  cors-origin: http://localhost:5173
  jwt-secret: VqvOe5l8t3yE8z0S8mJ0K4q0xKc9Y9oL9j6xBq8SgIc=
  jwt-ttl-days: 7

